# Generated by Django 2.1.2 on 2018-11-30 21:35

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='姓名')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='生产商')),
                ('address', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='地址')),
                ('production_origin', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='产地')),
                ('phone', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='电话')),
            ],
            options={
                'verbose_name': '生产商',
                'verbose_name_plural': '生产商',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='产品编号')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='品名')),
                ('logo', models.ImageField(blank=True, max_length=200, null=True, upload_to='./images', verbose_name='logo图片')),
                ('weight', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='净含量')),
                ('mixture', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='配料')),
                ('mixture_origin', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='原料产地')),
                ('mixture_country', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='原产国(地区)(原料)')),
                ('mixture_company', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='生产企业名称(原料)')),
                ('mixture_company_address', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='生产企业地址(原料)')),
                ('mixture_company_registration', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='生产企业注册号(原料)')),
                ('mixture_batch_number', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='生产批号(原料)')),
                ('mixture_production_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='生产日期(原料)')),
                ('mixture_expiration_date', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='保质期(原料)')),
                ('mixture_storage_conditions', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='贮藏条件(原料)')),
                ('mixture_format', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='规格(原料)')),
                ('mixture_destination', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='目的地(原料)')),
                ('executive_standard', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='产品执行标准')),
                ('production_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='生产日期')),
                ('expiration_date', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='保质期')),
                ('storage_conditions', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='贮藏条件')),
                ('authorized_agent', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='授权委托商')),
                ('authorized_agent_address', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='地址')),
                ('product_code', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='产品编码')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='printer.ManufacturerInfo', verbose_name='生产商'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
